name: control
dependencies:
- anaconda-client=1.0.2=py27_0
- astropy=1.0.4=np19py27_0
- clyent=0.4.0=py27_0
- freetype=2.5.2=2
- jpeg=8d=1
- libpng=1.6.17=0
- libtiff=4.0.2=1
- numpy=1.9.3=py27_0
- openssl=1.0.1k=1
- pillow=2.9.0=py27_0
- pip=7.1.2=py27_0
- pyserial=2.7=py27_0
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.6=py27_0
- pyyaml=3.11=py27_1
- readline=6.2=2
- requests=2.7.0=py27_0
- scipy=0.16.0=np19py27_1
- setuptools=18.3.2=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py27_0
- wxpython=3.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - wxpython-common==3.0.0.0

